#pragma config(Sensor, dgtl1,  SonarRight,     sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  SonarLeft,      sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  TouchLeft,      sensorTouch)
#pragma config(Sensor, dgtl9,  TouchRight,     sensorTouch)
#pragma config(Sensor, dgtl11, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*   This file is part of RobotC_Vex-Soccer-Goal
*
*   RobotC_Vex-Soccer-Goal is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   RobotC_Vex-Soccer-Goal is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with RobotC_Vex-Soccer-Goal.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
Task Description:
Keep count of score and show that by observing LED's when a button is pressed; a point should be added to the score each time a goal is made.
Psuedocode:
Set all variables used for scoring to "0".
Add a point to the score when an object passes by any of the two sonar sensors.
If a button or limit switch is pressed/flicked when there are no objects in range of the sonar sensor, report score.
*/

task main() {
    int score_green = 0;
    int score_red = 0;
    int g = 0;
    int r = 0;
    while (1 == 1) {
        if (SensorValue[SonarRight] < 14) {
            turnLEDOn(red);
            ++score_red;
        }
        if (SensorValue[SonarLeft] < 14) {
            turnLEDOn(green);
            ++score_green;
        }
        if (SensorValue[SonarRight] >= 14) {
            turnLEDOff(red);
            untilBump(TouchRight);
            if (r < score_red) {
                turnLEDOn(red);
                turnLEDOff(red);
                ++r;
            }
        }
        if (SensorValue[SonarLeft] >= 14) {
            turnLEDOff(green);
            untilBump(TouchLeft);
            if (g < score_green) {
                turnLEDOn(green);
                turnLEDOff(green);
                ++g;
            }
        }
    }
}
